### Cleaning Data Exercise: When we have missing values, outliers, inconsistent formatting, duplicates, invalid entries and etc.

In [1]:
import pandas as pd
import numpy as np

# Generating artificial sample data

np.random.seed(42) 

n = 10000  

df = pd.DataFrame({
    "OrderID": np.random.randint(1000, 2000, n), 
    "CustomerID": np.random.randint(1, 500, n),
    "Age": np.random.choice([20, 25, 30, 35, 40, None, -10], n),
    "Price": np.random.choice([10, 20, 50, 100, None, 9999], n),  
    "City": np.random.choice(["Berlin", "berlin", "BERLIN", "Munich", "munich", None, "Munchen"], n),
    "OrderDate": np.random.choice([
        "2023-01-10", "10/02/2023", "March 5 2023", None
    ], n),
    "Product": np.random.choice(["Laptop", "Phone", "Tablet", "phone ", " LAPTOP"], n),
    "Quantity": np.random.choice([1, 2, 3, 5, None, -1], n),
    "Email": np.random.choice([
        "test@gmail.com", "user@yahoo.com", "invalid_email", None
    ], n)
})

df.to_csv("real_world_dirty_data.csv", index=False)

In [2]:
#check the original unique values in a table before cleaning
df

,OrderID,CustomerID,Age,Price,City,OrderDate,Product,Quantity,Email
0,1102,442,40,20,munich,None,phone,-1,user@yahoo.com
1,1435,279,25,None,munich,March 5 2023,Laptop,None,user@yahoo.com
2,1860,251,20,20,Munich,None,Phone,3,invalid_email
3,1270,310,20,20,Berlin,10/02/2023,Phone,None,invalid_email
4,1106,208,30,20,Berlin,2023-01-10,LAPTOP,2,user@yahoo.com
...,...,...,...,...,...,...,...,...,...
9995,1914,390,35,10,None,March 5 2023,Phone,1,user@yahoo.com
9996,1209,444,25,9999,Munchen,None,Phone,2,None
9997,1740,301,35,9999,munich,2023-01-10,Laptop,None,user@yahoo.com
9998,1861,428,35,50,BERLIN,10/02/2023,Laptop,2,invalid_email
9999,1274,83,20,None,berlin,None,Laptop,3,user@yahoo.com

In [3]:
#check the overview of the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OrderID     10000 non-null  int32
 1   CustomerID  10000 non-null  int32
 2   Age         8558 non-null   object
 3   Price       8263 non-null   object
 4   City        8584 non-null   object
 5   OrderDate   7425 non-null   object
 6   Product     10000 non-null  object
 7   Quantity    8292 non-null   object
 8   Email       7456 non-null   object
dtypes: int32(2), object(7)
memory usage: 625.1+ KB

In [4]:
#check the number of missing values in each column
df.isna().sum()

OrderID          0
CustomerID       0
Age           1442
Price         1737
City          1416
OrderDate     2575
Product          0
Quantity      1708
Email         2544
dtype: int64

In [5]:
#check the statistical summary of the data
df.describe()

            OrderID    CustomerID
count  10000.000000  10000.000000
mean    1503.470600    248.579600
std      289.724434    144.146598
min     1000.000000      1.000000
25%     1250.000000    122.000000
50%     1505.500000    250.000000
75%     1757.000000    373.000000
max     1999.000000    499.000000

In [6]:
# Definition of median, mean and mode
[10, 20, 30, 40]

# median = (20 + 30) /2

[10, 20, 30, 40, 50]

# median = 30

# mean = (10 + 20 + 30 + +40 +50)/5

[10, 20, 30, 40, 50]

# mode = 30 #mode is the most frequently occurring value in a dataset. In this case, 30 appears more than any other number, making it the mode of the dataset.

[10, 20, 30, 40, 50]

In [39]:
data = [10, 20, 30, 40, 20, 1000]

#mean
mean_ = sum(data) / (len(data))
print(f"Mean : {mean_}")

#median
median_ = pd.Series(data).median()
print(f"Median : {median_}")

#mode
mode_ = pd.Series(data).mode()
print(f"Mode : {mode_}") # 0, in the result, is a Series index and mode() always returns a Series as it is just an indicator of the order which starts from 0.

Mean : 186.66666666666666
Median : 25.0
Mode : 0    20
dtype: int64

In [8]:
print(df["Age"].unique())

[40 25 20 30 -10 35 None]

In [ ]:
#clean "Age" column for non-numeric values
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Age"] = df["Age"].fillna(df["Age"].median()) #fillna is just to fill the missing values with the median of the column

In [40]:
print(df["Age"].unique())

[40. 25. 30. 20. 35. 10.]

In [ ]:
#clean "Price"" column for non-numeric values
df["Price"] = pd.to_numeric(df["Price"], errors="coerce")
df["Price"] = df["Price"].fillna(df["Price"].median()) #fillna is just to fill the missing values with the median of the column

In [12]:
print(df["Price"].unique())

[  20.   50. 9999.  100.   10.]

In [ ]:
#check the initial unique values in the "Quantity" column
print(df["Quantity"].unique())

[-1 None 3 2 1 5]

In [ ]:
#clean "Quantity" column for non-numeric values
df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce")
df["Quantity"] = df["Quantity"].fillna(0).astype(int) #fillna is just to fill the missing values with 0 and then convert the column to integer type

In [15]:
print(df["Quantity"].unique())

[-1  0  3  2  1  5]

In [ ]:
#check the initial unique values in the "City" column
print(df["City"].unique())

['munich' 'Munich' 'Berlin' 'Munchen' 'BERLIN' 'berlin' None]

In [17]:
df["City"] = df["City"].fillna("unknown") #in this time, fillna is just to fill the missing values with "unknown"

In [ ]:
#check the unique value in the "City" column after filling the missing values
print(df["City"].unique())

['munich' 'Munich' 'Berlin' 'Munchen' 'BERLIN' 'berlin' 'unknown']

In [ ]:
#check the initial unique values in the "OrderID" column
print(df["OrderID"].unique())

[1102 1435 1860 1270 1106 1071 1700 1020 1614 1121 1466 1214 1330 1458
 1087 1372 1099 1871 1663 1130 1661 1308 1769 1343 1491 1413 1805 1385
 1191 1955 1276 1160 1459 1313 1021 1252 1747 1856 1560 1474 1058 1510
 1681 1475 1699 1975 1782 1189 1957 1686 1562 1875 1566 1243 1831 1504
 1484 1818 1646 1840 1166 1273 1387 1600 1315 1013 1241 1776 1345 1564
 1897 1339 1091 1366 1454 1427 1508 1775 1942 1034 1205 1080 1931 1561
 1001 1389 1565 1105 1771 1821 1476 1702 1401 1729 1555 1161 1201 1995
 1269 1862 1815 1455 1461 1726 1251 1701 1295 1724 1719 1748 1337 1878
 1052 1791 1921 1216 1763 1187 1379 1492 1040 1156 1014 1812 1064 1838
 1520 1128 1647 1471 1062 1138 1498 1592 1391 1674 1418 1288 1378 1772
 1489 1230 1027 1134 1200 1839 1779 1929 1032 1047 1502 1406 1573 1727
 1804 1098 1683 1725 1986 1546 1960 1738 1612 1642 1768 1004 1217 1766
 1397 1870 1794 1392 1206 1857 1553 1891 1460 1690 1574 1863 1742 1240
 1563 1095 1899 1733 1654 1170 1540 1035 1524 1159 1698 1242 1085 1795
 1577 1556 1952 1645 1619 1797 1639 1505 1347 1472 1224 1384 1376 1282
 1632 1627 1972 1744 1258 1358 1709 1410 1648 1317 1676 1233 1974 1826
 1373 1671 1607 1232 1691 1112 1829 1496 1441 1267 1509 1806 1386 1624
 1951 1641 1219 1854 1996 1735 1402 1637 1129 1415 1246 1835 1438 1202
 1183 1122 1400 1293 1279 1836 1883 1609 1197 1981 1906 1751 1143 1608
 1123 1186 1325 1463 1348 1770 1659 1954 1962 1146 1147 1710 1819 1488
 1928 1935 1550 1640 1778 1987 1945 1150 1414 1989 1297 1610 1262 1623
 1571 1880 1896 1303 1253 1651 1452 1036 1008 1658 1207 1403 1151 1053
 1119 1672 1919 1586 1967 1419 1421 1103 1851 1226 1111 1152 1913 1895
 1877 1705 1162 1956 1680 1579 1800 1915 1503 1194 1687 1882 1469 1374
 1749 1669 1037 1229 1364 1437 1026 1225 1283 1959 1480 1828 1515 1048
 1511 1016 1171 1157 1045 1517 1301 1180 1606 1992 1115 1190 1980 1927
 1982 1255 1322 1127 1017 1792 1734 1569 1685 1625 1287 1853 1662 1961
 1638 1154 1985 1784 1810 1245 1175 1038 1758 1537 1866 1817 1920 1407
 1827 1902 1824 1684 1019 1320 1399 1653 1971 1470 1142 1353 1833 1799
 1958 1050 1664 1697 1124 1149 1341 1304 1837 1443 1263 1195 1773 1876
 1991 1349 1046 1822 1655 1268 1369 1635 1656 1830 1786 1603 1057 1950
 1740 1473 1116 1790 1126 1907 1633 1512 1750 1801 1117 1559 1487 1236
 1884 1271 1188 1998 1703 1446 1580 1789 1075 1153 1434 1696 1284 1973
 1068 1093 1203 1911 1431 1340 1611 1356 1022 1761 1521 1757 1179 1222
 1905 1324 1015 1335 1257 1689 1544 1426 1834 1576 1416 1167 1841 1042
 1396 1011 1753 1848 1089 1604 1969 1601 1417 1114 1616 1825 1500 1074
 1412 1375 1728 1760 1675 1393 1868 1456 1688 1547 1977 1368 1694 1278
 1872 1272 1061 1595 1879 1018 1176 1395 1444 1914 1264 1717 1383 1850
 1024 1947 1890 1468 1483 1568 1108 1692 1041 1185 1934 1132 1732 1234
 1842 1657 1587 1073 1953 1912 1518 1173 1652 1169 1193 1516 1028 1164
 1338 1495 1832 1499 1326 1300 1131 1803 1069 1181 1090 1713 1530 1125
 1450 1172 1894 1360 1000 1507 1408 1823 1933 1133 1814 1148 1079 1885
 1212 1228 1531 1440 1525 1970 1329 1783 1357 1667 1007 1177 1539 1731
 1739 1922 1501 1144 1723 1924 1908 1557 1593 1708 1449 1009 1250 1118
 1145 1223 1238 1852 1281 1104 1404 1976 1644 1869 1436 1457 1082 1084
 1077 1716 1445 1448 1033 1094 1249 1673 1305 1235 1388 1762 1302 1918
 1909 1737 1097 1849 1334 1858 1993 1307 1248 1165 1983 1541 1796 1137
 1545 1204 1746 1110 1182 1847 1519 1359 1695 1280 1666 1092 1060 1788
 1465 1533 1523 1944 1072 1793 1120 1213 1055 1572 1336 1025 1256 1718
 1215 1665 1311 1006 1002 1622 1362 1984 1630 1811 1536 1211 1066 1227
 1594 1424 1319 1442 1314 1965 1581 1136 1898 1542 1039 1005 1321 1467
 1003 1846 1605 1997 1946 1714 1299 1409 1139 1558 1549 1893 1867 1844
 1901 1260 1649 1012 1318 1328 1910 1816 1333 1994 1917 1290 1088 1294
 1615 1636 1864 1820 1578 1390 1178 1447 1668 1477 1096 1597 1634 1158
 1323 1843 1626 1754 1291 1010 1711 1140 1209 1682 1355 1887 1798 1377
 1904 1296 1813 1621 1949 1370 1660 1430 1968 1312 1936 1802 1346 1528
 1938 1966 1855 1155 1881 1083 1629 1722 1031 1428 1285 1423 1589 1174
 1113 1221 1677 1643 1054 1777 1978 1086 1327 1490 1451 1943 1774 1380
 1081 1513 1522 1745 1706 1939 1363 1631 1720 1208 1551 1277 1493 1598
 1628 1873 1286 1730 1575 1704 1743 1309 1405 1506 1481 1712 1497 1107
 1101 1865 1274 1043 1591 1990 1199 1570 1781 1371 1526 1721 1425 1310
 1780 1244 1439 1265 1925 1141 1292 1948 1584 1398 1888 1963 1583 1365
 1752 1889 1892 1266 1331 1462 1394 1900 1453 1964 1567 1261 1352 1344
 1030 1534 1926 1588 1988 1585 1411 1715 1078 1429 1886 1538 1381 1785
 1059 1590 1198 1535 1063 1494 1543 1552 1316 1859 1382 1514 1808 1903
 1306 1548 1351 1923 1861 1023 1937 1529 1736 1065 1275 1979 1932 1756
 1184 1192 1613 1916 1941 1220 1342 1618 1350 1582 1361 1049 1482 1076
 1596 1620 1707 1617 1247 1100 1930 1787 1767 1163 1109 1237 1845 1259
 1741 1422 1464 1231 1650 1210 1367 1168 1420 1029 1135 1999 1056 1940
 1765 1874 1532 1759 1678 1067 1679 1485 1433 1218 1602 1254 1479 1554
 1332 1239 1289 1478 1486 1809 1354 1044 1527 1755 1599 1432 1196 1693
 1298 1051 1070 1764 1670 1807]

In [ ]:
#removing duplicates
df = df.drop_duplicates(subset = "OrderID")

[1102 1435 1106 1614 1214 1087 1871 1663 1130 1343 1491 1805 1385 1313
 1021 1252 1747 1856 1560 1681 1782 1189 1957 1831 1504 1484 1818 1840
 1273 1241 1564 1897 1366 1508 1034 1001 1105 1401 1201 1726 1701 1295
 1719 1337 1878 1379 1040 1812 1647 1498 1592 1391 1418 1288 1378 1489
 1230 1134 1200 1839 1502 1727 1098 1642 1768 1004 1397 1794 1392 1553
 1891 1460 1863 1742 1899 1654 1170 1540 1524 1159 1698 1085 1645 1797
 1472 1224 1282 1627 1744 1358 1410 1676 1373 1671 1691 1829 1496 1441
 1386 1735 1402 1129 1415 1246 1202 1183 1122 1400 1279 1836 1883 1609
 1197 1751 1143 1608 1123 1325 1348 1770 1146 1147 1550 1987 1150 1414
 1297 1262 1571 1253 1452 1036 1658 1207 1053 1672 1919 1851 1111 1152
 1913 1895 1877 1705 1915 1503 1194 1687 1749 1669 1037 1229 1437 1026
 1959 1480 1515 1048 1301 1180 1992 1190 1255 1017 1792 1734 1569 1685
 1662 1638 1154 1784 1810 1245 1175 1038 1537 1866 1407 1827 1019 1971
 1470 1142 1799 1050 1195 1773 1876 1991 1822 1655 1268 1369 1635 1656
 1830 1786 1950 1116 1126 1907 1750 1801 1884 1998 1703 1580 1075 1284
 1973 1611 1521 1905 1257 1426 1834 1416 1042 1396 1011 1848 1089 1601
 1417 1074 1412 1728 1393 1868 1977 1595 1018 1395 1444 1264 1383 1850
 1947 1468 1568 1692 1732 1234 1842 1657 1587 1073 1953 1912 1193 1516
 1028 1164 1338 1499 1326 1069 1894 1000 1823 1933 1228 1531 1525 1970
 1783 1357 1723 1924 1908 1250 1118 1145 1852 1104 1976 1644 1084 1077
 1448 1033 1249 1305 1762 1097 1849 1334 1993 1307 1165 1137 1847 1060
 1944 1213 1256 1665 1002 1622 1362 1536 1211 1066 1594 1319 1442 1314
 1005 1321 1467 1605 1946 1139 1901 1649 1318 1816 1290 1615 1636 1390
 1477 1096 1634 1843 1754 1010 1209 1355 1904 1949 1370 1430 1346 1528
 1938 1881 1083 1285 1423 1589 1978 1086 1327 1451 1943 1380 1745 1939
 1720 1208 1575 1704 1405 1481 1990 1199 1371 1310 1439 1265 1141 1963
 1889 1266 1331 1964 1344 1534 1926 1588 1411 1429 1059 1494 1552 1859
 1903 1306 1548 1351 1923 1937 1529 1736 1275 1979 1756 1192 1613 1916
 1220 1342 1361 1482 1076 1163 1109 1237 1422 1231 1650 1210 1367 1135
 1999 1940 1532 1679 1485 1433 1254 1479 1239 1478 1486 1809 1527 1196]

In [21]:
print(df["Age"].unique())

[ 40.  25.  20.  30. -10.  35.]

In [ ]:
#abs function is used to get the absolute value of a number.
#abs(5) ===> 5
#abs(-5) ===> 5
#abs(0) ===> 0

df["Age"] = df["Age"].abs() #abs() function is used to convert negative values to positive values, and it leaves positive values and zero unchanged. In this case, it will convert any negative ages to their absolute values, ensuring that all ages are non-negative.
df["Age"] = df["Age"].apply(lambda x: abs(x)) # this is just another way to do the same thing as the previous above line.

C:\Users\swjun\AppData\Local\Temp\ipykernel_14056\3450696391.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Age"].abs() #abs() function is used to convert negative values to positive values, and it leaves positive values and zero unchanged. In this case, it will convert any negative ages to their absolute values, ensuring that all ages are non-negative.
C:\Users\swjun\AppData\Local\Temp\ipykernel_14056\3450696391.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Age"].apply(lambda x: abs(x)) # this is just another way to do the same thing as the previous above line.

In [23]:
print(df["Age"].unique())

[40. 25. 20. 30. 10. 35.]

In [44]:
#remove negative values from "Quantity" column.
df["Quantity"] = df["Quantity"].abs()

In [25]:
print(df["Quantity"].unique())

[1 0 3 2 5]

In [45]:
#check the original unique values in City column first
print(df["City"].unique())

['munich' 'berlin' 'munchen' 'unknown']

In [ ]:
df["City"] = df["City"].str.lower().str.strip() #this removes leading and trailing spaces and converts all city names to lowercase.
df["City"] = df["City"].replace({"Munchen" : "munich"}) #using dictionary ({}) to replace "Munchen" with "munich"

df.loc[: , "City"] = df["City"] = df["City"].str.lower().str.strip() #This is just another way to do as the 1st line
df.loc[: , "City"] = df["City"] = df["City"].replace({"Munchen" : "munich"}) #This is just another way to do as the 2nd line

In [28]:
print(df["Product"].unique())

['phone ' 'Laptop' 'Phone' ' LAPTOP' 'Tablet']

In [47]:
df["Product"] = df["Product"].str.lower().str.strip() #this removes leading and trailing spaces and converts all product names to lowercase.

In [30]:
print(df["Product"].unique())

['phone' 'laptop' 'tablet']

In [48]:
#Fix Date (Standardize everything under "OrderDate" into one format)

df["OrderDate"] = pd.to_datetime(df["OrderDate"], errors = "coerce")

In [49]:
print(df["OrderDate"].unique())

<DatetimeArray>
['NaT', '2023-03-05 00:00:00']
Length: 2, dtype: datetime64[ns]

In [33]:
#How to handle outliers: "Price" column has some outliers (e.g., 9999), we can remove it as it is not a realistic price for the products in our dataset.

df = df[df["Price"] <  1000] # remove rows where "Price" is greater than or equal to 1000

In [34]:
print(df["Price"].unique())

[ 20.  50. 100.  10.]

In [ ]:
#How to validate email addresses: we can use a simple regular expression pattern to check if the email addresses are in a valid format. In other words, we can check if the email contains "@" and "." characters.

df = df[df["Email"].str.contains("@", na = False)]

In [36]:
print(df["Email"].unique())

['user@yahoo.com' 'test@gmail.com']

In [ ]:
# How to create "Revenue" column. (Revenue = Price * Quantity) why do we need revenue?
# Creating Revenue is for us to analyze the total revenue generated from all orders in our dataset. By creating a "Revenue" column, we can easily calculate the total revenue for each order and then aggregate it to get insights into the overall performance of our sales.
 
df["Revenue"] = df["Price"] * df["Quantity"] #create a new column "Revenue".

In [ ]:
df #check the cleaned table with the new number of rows and columns (e.g., 10000 rows -> 420 rows), and the new "Revenue" column is added with the only acceptable values.

,OrderID,CustomerID,Age,Price,City,OrderDate,Product,Quantity,Email,Revenue
0,1102,442,40.0,20.0,munich,NaT,phone,1,user@yahoo.com,20.0
1,1435,279,25.0,50.0,munich,2023-03-05,laptop,0,user@yahoo.com,0.0
4,1106,208,30.0,20.0,berlin,NaT,laptop,2,user@yahoo.com,40.0
8,1614,34,40.0,100.0,berlin,NaT,laptop,5,test@gmail.com,500.0
11,1214,18,30.0,10.0,munich,NaT,phone,5,user@yahoo.com,50.0
...,...,...,...,...,...,...,...,...,...,...
4673,1478,16,25.0,100.0,berlin,NaT,phone,1,test@gmail.com,100.0
4821,1486,402,30.0,10.0,munich,2023-03-05,phone,2,test@gmail.com,20.0
4904,1809,173,25.0,10.0,unknown,NaT,phone,1,user@yahoo.com,10.0
4976,1527,322,30.0,10.0,munich,2023-03-05,phone,1,test@gmail.com,10.0
5893,1196,490,10.0,50.0,berlin,2023-03-05,laptop,1,user@yahoo.com,50.0